@startuml

[*] --> CREATED

CREATED --> INITIALIZING

INITIALIZING --> RUNNING
INITIALIZING --> CREATED
INITIALIZING --> STOPPED

RUNNING --> STOPPED
RUNNING --> FAILED

FAILED --> [*]
STOPPED --> [*]

@enduml

